### ISSUE TITLE
Calling `qh_pointid` safely without using `qhull_sys`

### ISSUE THREAD

**Issue by kmaitreys** [LucaCiucci/qhull-rs#7]
I cannot find a way to call the `qh_pointid` and some other functions such as `qh_setsize`. Following is a C code that I was trying to get working:
```C
if (checkSink) {
    FORALLfacets {
      if (!facet->upperdelaunay) {
        FOREACHneighbor_(facet) {
          if (neighbor->upperdelaunay) { /* This should indicate that facet lies
                                            on the edge of the model. */
            FOREACHvertex_(neighbor->vertices) {
              ppi = (unsigned long)qh_pointid(vertex->point);
              if (ppi < numPoints)
                gp[ppi].sink = 1;
            }
          }
        }
      }
    }
  }
```

In Rust,
```Rust
if check_sink {
        for face in qh.all_faces() {
            if !face.upper_delaunay() {
                let neighbors = face.neighbors().ok_or("Failed to get neighbors")?;
                for neighbor in neighbors.iter() {
                    if neighbor.upper_delaunay() {
                        let vertices = neighbor.vertices().ok_or("Failed to get vertices")?;
                        for vertex in vertices.iter() {
                            // ppi = vertex.id() is not what I want 
                            // `qh_pointid` does not return the `vertex.id`
                            if ppi < num_points {
                                gp[ppi].sink = 1;
                            }
                        }
                    }
                }
            }
        }
    }
```

I tried to call `sys::qh_pointid` but I am unable to get it working inside the `unsafe` block:
```Rust
unsafe {
        let qh = sys::qhT;
        ppi = sys::qh_pointid(qh, vertex.point().as_mut_ptr()) as usize;
    }
```

Maybe I can get the `unsafe` version working, but I would rather see if there is a way to get it through the `qhull-rs` itself.

Thanks in advance!

**Comment by LucaCiucci** [comment]
Hi @kmaitreys, unfortunately there is currently no way to call these functions using just `qhull-rs`.
I'll try to fix it right now.

**Comment by kmaitreys** [comment]
Thanks a lot for the quick reply @LucaCiucci ! And please, I am not sure how many functions there might be which are not exposed directly through `qhull-rs` and I really don't want to pressure you or anything. I just wanted to know that if there already was some way to use that function and I just could not find it. But yeah, it would be amazing if those functions are provided through `qhull-rs` someday.

Cheers!

**Comment by LucaCiucci** [comment]
I'm making some changes on branch `issue/7` to support these two functions and also improve access to the underlying `*sys::qhT`.
Once #8 gets merged the correct way to call Qhull functions is to use `Qh::try_on_qh` and `Qh::try_on_qh_mut` for fallible Qhull functions and `Qh::raw_ptr` for everything else.

For example, to call `qh_pointid` on a vertex:
```rs
let ptr = unsafe {
    let ptr = v.point().unwrap().as_ptr();
    Qh::try_on_qh(&qh, |qh| {
        qhull_sys::qh_pointid(qh as *mut _, ptr as *mut _)
    })
};
```
Note that `try_on_qh` is necessary in this specific case since `qh_pointid` can fail.

I'm sure there are tons of Qhull functions with no safe wrappers yet. If you find more please open issues/PR.

**Comment by kmaitreys** [comment]
Thank you very much @LucaCiucci , I got it working smoothly now (after fighting the borrow checker for a bit 😅 of course)!
